### ISSUE TITLE
Unable to get application logs

### ISSUE THREAD

**Issue by MichaelKunze** [ContainX/depcon#39]
I'm unable to get the logs of an app.

# depcon -e develop app log <app_id>
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x5be02b]

goroutine 1 [running]:
panic(0xadc060, 0xc820010110)
        /Users/junruh/go/src/runtime/panic.go:464 +0x3e6
github.com/ContainX/go-mesoslog/mesoslog.(*MesosClient).GetAppNameForTaskID(0x0, 0xc8203820a0, 0x42, 0x0, 0x0, 0x0, 0x0)
        /Users/junruh/Development/golang/src/github.com/ContainX/go-mesoslog/mesoslog/client.go:124 +0x4b
github.com/ContainX/depcon/commands/marathon.getMesosAppIdentifier(0xf81d60, 0x0, 0x7ffdc657e4ee, 0x1e, 0x0, 0x0)
        /Users/junruh/Development/golang/src/github.com/ContainX/depcon/commands/marathon/app_log_cmds.go:86 +0x1ef
github.com/ContainX/depcon/commands/marathon.showLogCmd(0xf81d60, 0xc82030bda0, 0x1, 0x3)
        /Users/junruh/Development/golang/src/github.com/ContainX/depcon/commands/marathon/app_log_cmds.go:48 +0x1a8
github.com/spf13/cobra.(*Command).execute(0xf81d60, 0xc82031cc00, 0x3, 0x4, 0x0, 0x0)
        /Users/junruh/Development/golang/src/github.com/spf13/cobra/command.go:499 +0x85a
github.com/spf13/cobra.(*Command).Execute(0xf7ee20, 0x0, 0x0)
        /Users/junruh/Development/golang/src/github.com/spf13/cobra/command.go:582 +0x46a
github.com/ContainX/depcon/commands.executeWithExistingConfig()
        /Users/junruh/Development/golang/src/github.com/ContainX/depcon/commands/depcon.go:138 +0x35d
github.com/ContainX/depcon/commands.Execute()
        /Users/junruh/Development/golang/src/github.com/ContainX/depcon/commands/depcon.go:77 +0x1ce
main.main()
        /Users/junruh/Development/golang/src/github.com/ContainX/depcon/main.go:26 +0x66

App-Id was removed to protect the innocent. The App-Id i'm using must be correct because depcon app get is working. All other commands are working as well.
Any Ideas?

**Comment by gondor** [comment]
What version of Mesos are you running? Does your app name have any symbols in it other than a "-"?

**Comment by MichaelKunze** [comment]
mesos version is 1.0.1
My app id contains slashes. Like /live/product/microservice. Is that a problem?

**Comment by gondor** [comment]
No that shouldn't be a problem since we use them in all of our clusters.  I haven't tested on 1.0.1, only 0.28.2.   

I'll have to setup  a small cluster to test this.

**Comment by gondor** [comment]
@MichaelKunze can't reproduce.  I created a cluster running 1.0.1 of mesos and 1.1.3 of Marathon and had no issues obtaining logs in a /path/likeyour/doing.  

If this app has multiple instances could you try the logs on an app that only has a single running instance.  The paths are slightly different when using the logs option.

**Comment by MichaelKunze** [comment]
Tried with a one instance app. Unfortunatly same result. Is there anything else i could provide? Maybe more debugging?
